[[education]]
institution = "DeVry University"
url = "https://devry.edu"
area = "Computer Information Systems"
studyType = "Bachelor of Science"
startDate = "1992-06-01"
endDate = "1995-06-15"
score = "3.75"

