[meta]
canonical = "https://raw.githubusercontent.com/jsonresume/resume-schema/v1.0.0/sample.resume.json"
version = "v1.0.1"
lastModified = "2025-05-15T15:53:00"
theme = "jsonresume-theme-stackoverflow"
