# [[projects]]
# name = "Miss Direction"
# description = "A mapping engine that misguides you"
# highlights = [ "Won award at AIHacks 2016", "Built by all women team of newbie programmers", "Using modern technologies such as GoogleMaps, Chrome Extension and Javascript",]
# keywords = [ "GoogleMaps", "Chrome Extension", "Javascript",]
# startDate = "2016-08-24"
# endDate = "2016-08-24"
# url = "http://missdirection.example.com"
# roles = [ "Team lead", "Designer",]
# entity = "Smoogle"
# type = "application"
