[[publications]]
name = "Video compression for 3d media"
publisher = "Hooli"
releaseDate = "2014-10-01"
summary = "Innovative middle-out compression algorithm that changes the way we store data."
url = "http://en.wikipedia.org/wiki/Silicon_Valley_(TV_series)"

