[[volunteer]]
endDate = "2013-01-01"
highlights = [ "Awarded 'Teacher of the Month'",]
organization = "CoderDojo"
position = "Teacher"
startDate = "2012-01-01"
summary = "Global movement of free coding clubs for young people."
url = "http://coderdojo.example.com/"

