[basics]
name = "Patrick A. Levell"
label = "Computer Systems Analyst"
image = "https://media.licdn.com/dms/image/v2/D5603AQHZAOi4imti3Q/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1675029596103?e=1752710400&v=beta&t=PYdbayMEPFGRIBRgb_WPKjkRJ0L5_dfDLiH170DJnSM"
email = "patrick@levell.tech"
url = "https://levell.tech"
summary = "Results-driven Systems Analyst / Developer, Business Analyst, and Bitcoin enthusiast with broad-based experience in enhancing system functionality and end-user productivity. Accomplished professional who has earned a reputation for consistently meeting and exceeding aggressive objectives. Effective communicator possessing excellent interpersonal and relationship-building skills."

[[basics.profiles]]
network = "LinkedIn"
url = "https://linkedin.com/in/palevell"

[basics.location]
postalCode = "N6J 3R5"
city = "London"
countryCode = "CA"
region = "Ontario"

[[work]]
name = "Pied Piper"
location = "Palo Alto, CA"
description = "Awesome compression company"
position = "CEO/President"
url = "http://piedpiper.example.com"
startDate = "2013-12-01"
endDate = "2014-12-01"
summary = "Pied Piper is a multi-platform technology based on a proprietary universal compression algorithm that has consistently fielded high Weisman Scores™ that are not merely competitive, but approach the theoretical limit of lossless compression."
highlights = [ "Build an algorithm for artist to detect if their music was violating copy right infringement laws", "Successfully won Techcrunch Disrupt", "Optimized an algorithm that holds the current world record for Weisman Scores",]

[[volunteer]]
endDate = "2013-01-01"
highlights = [ "Awarded 'Teacher of the Month'",]
organization = "CoderDojo"
position = "Teacher"
startDate = "2012-01-01"
summary = "Global movement of free coding clubs for young people."
url = "http://coderdojo.example.com/"

[[education]]
institution = "DeVry University"
url = "https://devry.edu"
area = "Computer Information Systems"
studyType = "Bachelor of Science"
startDate = "1992-06-01"
endDate = "1995-06-15"
score = "3.75"

[[awards]]
awarder = "Techcrunch"
date = "2014-11-01"
summary = "There is no spoon."
title = "Digital Compression Pioneer Award"

[[publications]]
name = "Video compression for 3d media"
publisher = "Hooli"
releaseDate = "2014-10-01"
summary = "Innovative middle-out compression algorithm that changes the way we store data."
url = "http://en.wikipedia.org/wiki/Silicon_Valley_(TV_series)"

[[skills]]
name = "Programming"
level = "Proficient"
keywords = [ "BASH", "C", "HTML", "Python", "SQL",]

[[skills]]
name = "Programming"
level = "Experienced"
keywords = [ "C++", "CSS", "JavaScript", "PHP",]

[[skills]]
name = "Programming"
level = "Familiar"
keywords = [ "GO",]

[[skills]]
name = "Libraries/Frameworks"
level = "Proficient"
keywords = [ "Flask", "Django", "Pandas", "SQLAlchemy",]

[[skills]]
name = "Libraries/Frameworks"
level = "Experienced"
keywords = [ "Jekyll", "Hugo", "Node.JS",]

[[skills]]
name = "Libraries/Frameworks"
level = "Familiar"
keywords = [ "Laravel", "PyQt6", "Tailwind CSS",]

[[skills]]
name = "Tools/Platforms"
level = "Proficient"
keywords = [ "PyCharm", "VScode", "WordPress",]

[[skills]]
name = "Tools/Platforms"
level = "Experienced"
keywords = [ "Emacs", "Git", "JD Edwards / EnterpriseOne",]

[[skills]]
name = "Tools/Platforms"
level = "Familiar"
keywords = [ "Apache", "Docker", "Heroku", "NginX",]

[[languages]]
fluency = "Native speaker"
language = "English"

[[interests]]
keywords = [ "Ferrets", "Unicorns",]
name = "Wildlife"

[[references]]
name = "Upon request"

[[projects]]
description = "A mapping engine that misguides you"
endDate = "2016-08-24"
entity = "Smoogle"
highlights = [ "Won award at AIHacks 2016", "Built by all women team of newbie programmers", "Using modern technologies such as GoogleMaps, Chrome Extension and Javascript",]
keywords = [ "GoogleMaps", "Chrome Extension", "Javascript",]
name = "Miss Direction"
roles = [ "Team lead", "Designer",]
startDate = "2016-08-24"
type = "application"
url = "http://missdirection.example.com"

[meta]
canonical = "https://raw.githubusercontent.com/jsonresume/resume-schema/v1.0.0/sample.resume.json"
lastModified = "2025-05-14T11:17:34-04:00"
version = "v1.0.0"
